"""Generate the fixed UI's 4-bit coverage glyphs; Pillow runs only on the host.

Source: Noto Sans CJK SC Regular, SIL OFL 1.1 (font-source/LICENSE).
The OTF is an offline build input, never linked into the firmware.
"""
from pathlib import Path
import hashlib
import json
from PIL import Image, ImageDraw, ImageFont
from prepare_kk_assets import TEXT, TITLE_TEXT

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'tools/font-source/NotoSansCJKsc-Regular.otf'
OUT = ROOT / 'components/gl30_ui/assets'
chars = ''.join(sorted(set(TEXT + TITLE_TEXT)))
faces = [(28, chars), (34, chars), (68, '0123456789:.-% °'),
         (24, chars), (96, '0123456789:- ')]
data, glyphs, counts = [], [], []
for size, alphabet in faces:
    font = ImageFont.truetype(str(SOURCE), size)
    counts.append(len(glyphs))
    for ch in sorted(set(alphabet)):
        left, top, right, bottom = font.getbbox(ch, anchor='ls')
        width, height = right-left, bottom-top
        picture = Image.new('L', (max(width, 1), max(height, 1)))
        ImageDraw.Draw(picture).text((-left, -top), ch, font=font, fill=255, anchor='ls')
        coverage = [(p+8)//17 for p in picture.getdata()] if width*height else []
        start = len(data)
        # RLE tokens: high nibble = run length minus one, low nibble = coverage.
        # End each run at its row boundary so the target can write solid spans.
        for row in range(height):
            x = 0
            while x < width:
                a = coverage[row*width+x]
                end = x+1
                while end < min(width, x+16) and coverage[row*width+end] == a:
                    end += 1
                data.append(((end-x-1)<<4) | a)
                x = end
        glyphs.append((ord(ch), start, width, height, left, top+round(size*.88), round(font.getlength(ch))))
counts.append(len(glyphs))
lines = ['/* Generated by tools/prepare_ui_type.py; Noto Sans CJK SC / SIL OFL 1.1. */',
         '#include "gl30_type.h"', 'const uint8_t gl30_type_pixels[] = {']
lines += [','.join(str(n) for n in data[i:i+40])+',' for i in range(0, len(data), 40)]
lines += ['};', 'const gl30_type_glyph gl30_type_glyphs[] = {']
lines += ['{'+','.join(str(v) for v in g)+'},' for g in glyphs]
lines += ['};', 'const uint16_t gl30_type_starts[6] = {'+','.join(map(str, counts))+'};', '']
(OUT/'gl30_type_data.c').write_text('\n'.join(lines), encoding='utf-8')
(OUT/'noto-OFL.txt').write_bytes((SOURCE.parent/'LICENSE').read_bytes())
report = {'source': 'https://github.com/notofonts/noto-cjk/blob/main/Sans/OTF/SimplifiedChinese/NotoSansCJKsc-Regular.otf',
          'sha256': hashlib.sha256(SOURCE.read_bytes()).hexdigest(), 'coverage_bits': 4,
          'rle_bytes': len(data), 'glyphs': len(glyphs), 'sizes': [s for s, _ in faces]}
(OUT/'type-generation.json').write_text(json.dumps(report, indent=2), encoding='utf-8')
print(json.dumps(report))
